[package]
name = "file_nif"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]
bench= false

[dependencies]
rustler = "0.23.0"
